Parameters for advanced item and label styling of tree nodes
uhafner/echarts-build-trends pull request #215
Opened 2022-09-18 13:11 UTC by fo-code

I added additional parameters in order to be able to specifically style borders and labels of tree nodes.
These are useful for also styling outer tree nodes with children for example.

Initially, I used the default values from the echarts documentation if these parameters are not set specifically.
This might override level stylings which are done in Javascript files.
Maybe it would be an option to set these not specifically set values to `null` in order to avoid this, @uhafner ?
What do you prefer here?

2022-09-19 19:43 UTC, uhafner commented
> Initially, I used the default values from the echarts documentation if these parameters are not set specifically.
This might override level stylings for tree maps which are specified in Javascript files.

Do we have those maps already? Currently, the code coverage plugin is the only user of these charts.

> Maybe it would be an option to set these not specifically set values to null in order to avoid this, @uhafner ?
What do you prefer here?

I think this is not required. If someone complains we can add that later.

2022-09-19 19:43 UTC, uhafner requested changes

2022-09-19 19:43 UTC, uhafner commented on src/main/java/edu/hm/hafner/echarts/UpperLabel.java
> +public class UpperLabel {
Why is this a copy of the `Label` class? Can't we simply have a property `upperLabel` of the `Label` in class `TreeMapNode`?

2022-09-19 19:43 UTC, uhafner commented on src/test/java/edu/hm/hafner/echarts/TreeMapNodeTest.java
> +                label -> assertThat(label.getShow()).isEqualTo(false),
```suggestion
                label -> assertThat(label.getShow()).isFalse(),
```

2022-09-19 20:55 UTC, fo-code commented
> Do we have those maps already? Currently, the code coverage plugin is the only user of these charts.

No, not within the coverage plugin. I just wanted to mention it because I did not know if this is in use in other plugins. :)

2022-09-21 08:26 UTC, uhafner approved these changes

2022-09-21 08:33 UTC, merged

2022-09-21 11:51 UTC, uhafner commented
After locally installing the tree charts are now broken (no label). That means we need to release both changes in sync:

![Bildschirmfoto 2022-09-21 um 13 49 39](https://user-images.githubusercontent.com/503338/191496792-7201d7de-0497-440f-8e41-90807bbfdee4.png)